
services:
  client:
    build:
      context: ./client
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server
    command: npm run dev
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 785M

  server:
    build:
      context: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env
    command: npm run dev
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M


